local_repository(
    name = "org_pubref_rules_node",
    path = "../..",
)

load("@org_pubref_rules_node//node:rules.bzl", "node_repositories", "yarn_modules")

node_repositories()

yarn_modules(
    name = "protobuf_modules",
    deps = {
        "google-protobuf": "3.4.0"
    }
)

yarn_modules(
    name = "mocha_modules",
    deps = {
        "mocha": "4.0.1"
    }
)

http_archive(
    name = "com_google_protobuf",
    urls = ["https://github.com/google/protobuf/archive/v3.4.0.zip"],
    strip_prefix = "protobuf-3.4.0",
    sha256 = "542703acadc3f690d998f4641e1b988f15ba57ebca05fdfb1cd9095bec007948"
)
