local_repository(
    name = "org_pubref_rules_node",
    path = "../..",
)

load("@org_pubref_rules_node//node:rules.bzl", "node_repositories", "yarn_modules")

node_repositories()

yarn_modules(
    name = "yarn_modules",
    deps = {
        "ref": "1.3.5",
    },
    # yarn install of 'ref' triggers node-gyp. This will in turn
    # require 'sh' and 'dirname'.  Explicitly make these tools
    # available during the yarn install step.
    install_tools = [
        "sh", # /bin
        "dirname", # #/usr/bin
    ],
)
