package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_node//node:rules.bzl", "node_module")

node_module(
    name = "answer",
    index = "index.js",
    namespace = "@pubref",
    module_name = "meaning_of_life",
)
