load("//node:internal/node_repositories.bzl", "node_repositories")
load("//node:internal/npm_repository.bzl", "npm_repository")
load("//node:internal/bower_repository.bzl", "bower_repository")
load("//node:internal/node_binary.bzl", "node_binary")
load("//node:internal/node_library.bzl", "node_library")
load("//node:internal/mocha_test.bzl", "mocha_test")
