load("//node:internal/node_repositories.bzl", "node_repositories")
load("//node:internal/node_binary.bzl", "node_binary")
load("//node:internal/node_library.bzl", "node_library")
load("//node:internal/npm_repository.bzl", "npm_repository")
load("//node:internal/npm_library.bzl", "npm_library")
load("//node:internal/npm_registry.bzl", "npm_registry")
