package(default_visibility = ["//visibility:public"])

sh_test(
    name = "polymer-cli_bin_test",
    size = "small",
    srcs = ["polymer-cli_bin_test.sh"],
	data = ["@yarn_modules//:polymer-cli_polymer_bin"],
)

