workspace(name = "org_pubref_rules_node_polymer_test")

local_repository(
    name = "org_pubref_rules_node",
    path = "../..",
)

load("@org_pubref_rules_node//node:rules.bzl", "node_repositories", "yarn_modules")

node_repositories()

yarn_modules(
    name = "yarn_modules",
    deps = {
        "polymer-cli": "1.5.7",
        "update-notifier": "1.0.3",
    },
)
