local_repository(
    name = "org_pubref_rules_node",
    path = "../..",
)

load("@org_pubref_rules_node//node:rules.bzl", "node_repositories", "yarn_modules")

node_repositories()

yarn_modules(
    name = "yarn_modules",
    deps = {
        "typescript": "2.5.2",
        "@types/node": "8.0.28",
    }
)
